# Generated by Django 4.2.29 on 2026-04-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, verbose_name='Гендер')),
            ],
        ),
    ]
